openapi: 3.0.0
info:
  title: Lego Ecommerce API
  version: 1.0.0
paths:
  /products:
    get:
      summary: List products
      parameters:
        - in: query
          name: search
          schema: { type: string }
        - in: query
          name: theme
          schema: { type: string }
        - in: query
          name: minPrice
          schema: { type: number }
        - in: query
          name: maxPrice
          schema: { type: number }
      responses:
        '200': { description: OK }
  /cart/items:
    post:
      summary: Add item to cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId: { type: integer }
                quantity: { type: integer }
      responses:
        '200': { description: OK }
  /cart/items/{id}:
    patch:
      summary: Update cart item
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity: { type: integer }
      responses:
        '200': { description: OK }
  /orders:
    post:
      summary: Create order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                couponCode: { type: string }
      responses:
        '200': { description: OK }
  /payments/mp/preference:
    post:
      summary: Create Mercado Pago preference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId: { type: integer }
      responses:
        '200': { description: OK }
  /webhooks/mp:
    post:
      summary: Mercado Pago webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentId: { type: string }
                status: { type: string }
      responses:
        '200': { description: OK }
